plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.7
  NewCops: enable
  SuggestExtensions: true
  Exclude:
    - '**/spec/**/*'
    - '**/config/**/*'
    - '**/lib/**/*'
    - '**/vendor/**/*'
    - '**/db/**/*'
    - '**/log/**/*'
    - '**/public/**/*'
    - '**/tmp/**/*'
    - '**/config/database.yml'
    - '**/config/puma.rb'
    - '**/config/routes.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
