# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  port: <%= ENV['DB_PORT'] || 5432 %>
  pool: <%= ENV.fetch('DB_MAX_THREADS') { 5 } %>
  host: <%= ENV['DB_HOST'] || '0.0.0.0' %>
  username: <%= ENV['DB_USER'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'secret' %>

development:
  <<: *default
  database: <%= ENV['DEV_DB_NAME'] || 'weather_dev' %>

test:
  <<: *default
  database: <%= ENV['TEST_DB_NAME'] || 'weather_test' %>

production:
  <<: *default
  database: <%= ENV['PROD_DB_NAME'] || 'weather_prod' %>
